"""add composite indexes on sensor tables

Revision ID: 405c037bf903
Revises: a00cd7251333
Create Date: 2026-08-17 23:42:32.228939
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '405c037bf903'
down_revision: Union[str, None] = 'a00cd7251333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ath_gh_ts', 'air_temperature_humidity', ['greenhouse_id', 'timestamp'], unique=False)
    op.create_index('ix_li_gh_ts', 'light_intensity', ['greenhouse_id', 'timestamp'], unique=False)
    op.create_index('ix_sm_gh_ts', 'soil_moisture', ['greenhouse_id', 'timestamp'], unique=False)
    op.create_index('ix_sn_gh_ts', 'soil_nutrient', ['greenhouse_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sn_gh_ts', table_name='soil_nutrient')
    op.drop_index('ix_sm_gh_ts', table_name='soil_moisture')
    op.drop_index('ix_li_gh_ts', table_name='light_intensity')
    op.drop_index('ix_ath_gh_ts', table_name='air_temperature_humidity')
    # ### end Alembic commands ###
