"""initial schema

Revision ID: a00cd7251333
Revises:
Create Date: 2026-08-17 20:50:18.619341
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a00cd7251333'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greenhouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_time', sa.DateTime(), nullable=False),
    sa.Column('log_level', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_action_type'), 'operation_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_log_time'), 'operation_logs', ['log_time'], unique=False)
    op.create_index(op.f('ix_operation_logs_username'), 'operation_logs', ['username'], unique=False)
    op.create_table('air_temperature_humidity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_temperature_humidity_greenhouse_id'), 'air_temperature_humidity', ['greenhouse_id'], unique=False)
    op.create_index(op.f('ix_air_temperature_humidity_timestamp'), 'air_temperature_humidity', ['timestamp'], unique=False)
    op.create_table('light_intensity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_light_intensity_greenhouse_id'), 'light_intensity', ['greenhouse_id'], unique=False)
    op.create_index(op.f('ix_light_intensity_timestamp'), 'light_intensity', ['timestamp'], unique=False)
    op.create_table('soil_moisture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_moisture_greenhouse_id'), 'soil_moisture', ['greenhouse_id'], unique=False)
    op.create_index(op.f('ix_soil_moisture_timestamp'), 'soil_moisture', ['timestamp'], unique=False)
    op.create_table('soil_nutrient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_nutrient_greenhouse_id'), 'soil_nutrient', ['greenhouse_id'], unique=False)
    op.create_index(op.f('ix_soil_nutrient_timestamp'), 'soil_nutrient', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('last_login_time', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('admin_request', sa.Boolean(), nullable=False),
    sa.Column('admin_request_time', sa.DateTime(), nullable=True),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_soil_nutrient_timestamp'), table_name='soil_nutrient')
    op.drop_index(op.f('ix_soil_nutrient_greenhouse_id'), table_name='soil_nutrient')
    op.drop_table('soil_nutrient')
    op.drop_index(op.f('ix_soil_moisture_timestamp'), table_name='soil_moisture')
    op.drop_index(op.f('ix_soil_moisture_greenhouse_id'), table_name='soil_moisture')
    op.drop_table('soil_moisture')
    op.drop_index(op.f('ix_light_intensity_timestamp'), table_name='light_intensity')
    op.drop_index(op.f('ix_light_intensity_greenhouse_id'), table_name='light_intensity')
    op.drop_table('light_intensity')
    op.drop_index(op.f('ix_air_temperature_humidity_timestamp'), table_name='air_temperature_humidity')
    op.drop_index(op.f('ix_air_temperature_humidity_greenhouse_id'), table_name='air_temperature_humidity')
    op.drop_table('air_temperature_humidity')
    op.drop_index(op.f('ix_operation_logs_username'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_log_time'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action_type'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('greenhouse')
    # ### end Alembic commands ###
